### ISSUE TITLE
2nd-try: Error: thread 'main' panicked at 'called Result::unwrap() on an Err value: NotSupported', src/metrics.rs:160:50

### ISSUE THREAD

**Issue by maltokyo** [cloutreactor/release#13]
This: https://github.com/cloutreactor/release/issues/7 Did not get resolved at all with v0.0.2, why did you close it?

Could we please close issues when they are tested and resolved.  Collaborating here is not fun so far.

log:

```
root@pc:~# docker run --rm --name cloutreactor --gpus all --runtime nvidia cloutreactor/cuda:v0.0.2 --public-key="MYPUBKEYREMOVED"
Unable to find image 'cloutreactor/cuda:v0.0.2' locally
v0.0.2: Pulling from cloutreactor/cuda
a70d879fa598: Already exists 
c4394a92d1f8: Already exists 
10e6159c56c0: Already exists 
f1ff119ac131: Already exists 
82d43a3edcbe: Already exists 
6d2cde93abc2: Already exists 
8f90d4cd8f39: Already exists 
99f595cc37b3: Already exists 
061850a0b036: Already exists 
fc2502208f01: Pull complete 
Digest: sha256:44a12b4468b73f28fe370a111df58792753bf2cbaad80f9e334f944e55201a94
Status: Downloaded newer image for cloutreactor/cuda:v0.0.2
[2021-05-26T06:21:54Z INFO  cloutreactor::controller] cloutreactor started...
[2021-05-26T06:21:59Z INFO  cloutreactor::metrics] GPU[0] --Mh/s (0W)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', src/metrics.rs:160:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-05-26T06:22:04Z INFO  cloutreactor::metrics] GPU[0] 27.17Mh/s (0W)
[2021-05-26T06:22:09Z INFO  cloutreactor::metrics] GPU[0] 54.12Mh/s (0W)
```

**Comment by korbin** [comment]
This issue was a pool stability issue and is fixed.
