### ISSUE TITLE
Error: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', src/metrics.rs:160:50

### ISSUE THREAD

**Issue by maltokyo** [cloutreactor/release#7]
When I run, I get this error: `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', src/metrics.rs:160:50`

Only at the start, then it seems that it actually does start mining anyway.  Please advise if I can ignore this?

```
root@msi:~# docker run --rm --name cloutreactor --gpus all --runtime nvidia cloutreactor/cuda:latest --public-key="MYPUBKEY_REMOVED"
[2021-05-25T09:48:00Z INFO  cloutreactor::controller] cloutreactor started...
[2021-05-25T09:48:05Z INFO  cloutreactor::metrics] GPU[0] --Mh/s (0W)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', src/metrics.rs:160:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-05-25T09:48:10Z INFO  cloutreactor::metrics] GPU[0] 27.14Mh/s (0W)
```

**Comment by korbin** [comment]
The pool was having momentary issues due to increased load - version 0.0.2 addresses these scenarios.
